### ISSUE TITLE
Unable to set port format when using MMAL_ENCODING_PNG

### ISSUE THREAD

**Issue by crsaracco** [pedrosland/rascam#4]
If I copy/paste the `serious.rs` example, and replace `MMAL_ENCODING_RGB24` with `MMAL_ENCODING_PNG`, I get the following runtime error:

```
mmal: mmal_vc_port_info_set: failed to set port info (3:2): EINVAL
mmal: mmal_vc_port_set_format: mmal_vc_port_info_set failed 0x1972220 (EINVAL)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CameraError(Mmal(MmalError { message: Unable to set still port format, status: EINVAL, status_code: 3 }))', src/main.rs:39:5
```

I'm not too familiar with MMAL or the protocol that the RPi camera speaks, and there isn't a lot of documentation surrounding this error or API in the docs, so I'm not really sure what's wrong here.

Is this supposed to work, or is failure here expected?

Thanks!

**Comment by pedrosland** [comment]
> there isn't a lot of documentation surrounding this error

Indeed.

In order to use some kind of non-raw-like image format, such as jpeg or png, we need to set up the pipeline with an encoder. We can do that by setting `use_encoder: true` when we pass `CameraSettings` to `set_camera_format`.

Unless you want the extra flexibility provided by `SeriousCamera`, it might be more convenient to use `SimpleCamera`. It also takes the same CameraSettings object in `configure` and since `use_encoder` defaults to true we can modify the simple.rs example:
```
    let mut camera = SimpleCamera::new(info.clone()).unwrap();
    camera.configure(CameraSettings{
        encoding: MMAL_ENCODING_PNG,
        ..CameraSettings::default()
    });
    camera.activate().unwrap();
```

If you want to use `SeriousCamera`, you also need to call the methods to create and enable the encoder. SimpleCamera always expects the `use_encoder: true` at present so you can look at its implementation for inspiration.

Ideally `use_encoder` would be removed as it could be auto-detected for SimpleCamera and irrelevant for SeriousCamera.

While not an issue with what you are doing, it is worth pointing out that some of the video encoding options are no longer available on the Pi4. If I remember correctly H264 is fine but H263 and some others were removed and H265 (new for Pi4) isn't hooked up for MMAL but is available using v4l2.
